[SBS] Add autocomplete

diff --git a/sbs b/sbs
--- a/sbs
+++ b/sbs
@@ -643,6 +643,14 @@ lint() {
 }
 
 format() {
+    flags=$(filter_flags "$@")
+    args=$(filter_args "$@")
+
+    known_flags=()
+
+    cmd_flags known_flags[@] flags[@] || return
+    cmd_args 0 $args || return
+
     step "formatting"
 
     echo "Running clang-format..."
@@ -658,18 +666,20 @@ help() {
     echo "Usage: sbs (command) <args> [options] "
     echo ""
     echo "Commands:"
-    echo " build  - Build the specified target"
-    echo "        -> <target=all> [-d|--debug] [-v|--verbose] [-h|--host] [-j|--jobs=<jobs>]"
-    echo " clean  - Clean the build directory"
-    echo "        -> [-h|--host]"
-    echo " flash  - Flash the specified target"
-    echo "        -> <target> [-d|--debug] [-v|--verbose] [-j|--jobs=<jobs>]"
-    echo " test   - Run the tests for the specified target"
-    echo "        -> <target> [-j|--jobs=<jobs>]"
-    echo " list   - List the available targets or boards"
-    echo "        -> <targets|boards>"
-    echo " lint   - Lint the source code"
-    echo " format - Format the source code"
+    echo " build     - Build the specified target"
+    echo "           -> <target=all> [-d|--debug] [-v|--verbose] [-h|--host] [-j|--jobs=<jobs>]"
+    echo " clean     - Clean the build directory"
+    echo "           -> [-h|--host]"
+    echo " flash     - Flash the specified target"
+    echo "           -> <target> [-d|--debug] [-v|--verbose] [-j|--jobs=<jobs>]"
+    echo " test      - Run the tests for the specified target"
+    echo "           -> <target> [-j|--jobs=<jobs>]"
+    echo " list      - List the available targets or boards"
+    echo "           -> <targets|boards>"
+    echo " lint      - Lint the source code"
+    echo " format    - Format the source code"
+    echo " install   - Install autocomplete"
+    echo " uninstall - Uninstall autocomplete"
     echo ""
     echo "Options:"
     echo " -d, --debug:   Build in debug mode"
@@ -683,6 +693,59 @@ help() {
 ##############################   Python Commands  ##############################
 ################################################################################
 
+
+install() {
+    flags=$(filter_flags "$@")
+    args=$(filter_args "$@")
+
+    known_flags=()
+
+    cmd_flags known_flags[@] flags[@] || return
+    cmd_args 0 $args || return
+
+    step "autocomplete"
+
+    if [ "$found_python" = false ]; then
+        echo ""$ERR": Python is required to install autocomplete"
+        return 1
+    fi
+
+    config_host=false
+    config_debug=false
+    config_verbose=false
+    build_dir="$build_default_dir"
+
+    echo "Retrieving targets..."
+
+    targets=$(cmake --build "$build_dir" --target help \
+        | grep -o '^[^/]*\.bin' | cut -f 1 -d '.')
+
+    # split the targets on newlines
+    IFS=$'\n' read -rd '' -a targets <<< "$targets"
+
+    echo "Found ${#targets[@]} targets"
+
+    python "$sbs_base/scripts/autocomplete.py" "--install" "${targets[@]}"
+}
+
+uninstall() {
+    flags=$(filter_flags "$@")
+    args=$(filter_args "$@")
+
+    known_flags=()
+
+    cmd_flags known_flags[@] flags[@] || return
+    cmd_args 0 $args || return
+
+    step "autocomplete"
+
+    if [ "$found_python" = false ]; then
+        echo ""$ERR": Python is required to uninstall autocomplete"
+        return 1
+    fi
+
+    python "$sbs_base/scripts/autocomplete.py" "--uninstall"
+}
 
 ################################################################################
 ##############################        Main        ##############################
@@ -699,14 +762,16 @@ init() {
 
 for arg in "$@"; do
     case $arg in
-        build)  init; build "${@:2}"; exit ;;
-        clean)  init; clean "${@:2}"; exit ;;
-        flash)  init; flash "${@:2}"; exit ;;
-        test)   init; test  "${@:2}"; exit ;;
-        list)   init; list  "${@:2}"; exit ;;
-        lint)   init; lint  "${@:2}"; exit ;;
-        format) init; format; exit ;;
-        *)      help; exit ;;
+        build)     init; build "${@:2}"; exit ;;
+        clean)     init; clean "${@:2}"; exit ;;
+        flash)     init; flash "${@:2}"; exit ;;
+        test)      init; test  "${@:2}"; exit ;;
+        list)      init; list  "${@:2}"; exit ;;
+        lint)      init; lint  "${@:2}"; exit ;;
+        format)    init; format; exit ;;
+        install)   init; install; exit ;;
+        uninstall) init; uninstall; exit ;;
+        *)         help; exit ;;
     esac
 done
 
